baseurl = "https://www.rafaelstern.science/"
languageCode = "en-us"
title = "Rafael Bassi Stern"
theme = "blackburn"
author = "Yoshiharu Yamashita"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  brand = "Rafael Stern"
  googleAnalytics = "UA-114310932-1"
  disqus = "rafaelstern"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 10
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Research"
    pre = "<i class='fa fa-cogs fa-fw'></i>"
    weight = 20
    identifier = "research"
    url = "/research/"
  [[menu.main]]
    name = "Groups"
    pre = "<i class='fa fa-users-cog fa-fw'></i>"
    weight = 25
    identifier = "groups"
    url = "/groups/"
  [[menu.main]]
    name = "Teaching"
    pre = "<i class='fa fa-university fa-fw'></i>"
    weight = 30
    identifier = "teaching"
    url = "/teaching/"
  [[menu.main]]
    name = "Students"
    pre = "<i class='fa fa-baby fa-fw'></i>"
    weight = 40
    identifier = "students"
    url = "/students/"
  [[menu.main]]
    name = "Resources"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 50
    identifier = "resources"
    url = "/resources/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 60
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-envelope fa-fw'></i>"
    weight = 70
    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  github = "rbstern"
  googlescholar = "2iLil_kAAAAJ"
  lattes = "K4282979H6"
  mathexchange = "34305"
