---
date: "2022-08-14"
title: "Notas"
highlight: true
output: html_document
type: book
---

## Tabela de notas

- OBS: Notas são indexadas pelos últimos 3 dígitos do número USP.

```{r echo = FALSE, warning = FALSE, message = FALSE}
library(DT)
library(tidyverse)
library(widgetframe)
data = read_csv("./grades.csv") %>% 
  filter((P1 + P2 + P3 + Sub) != 0) %>%
  mutate(MF1 = 0.3*P1 + 0.3*P2 + 0.35*P3 + Part,
         MF2 = 0.3*Sub + 0.3*P2 + 0.35*P3 + Part,
         MF3 = 0.3*P1 + 0.3*Sub + 0.35*P3 + Part,
         MF4 = 0.3*P1 + 0.3*P2 + 0.35*Sub + Part,
         MF = pmax(MF1, MF2, MF3, MF4),
         MF = ceiling(10*MF)/10) %>% 
  select(-MF1, -MF2, -MF3, -MF4) %>% 
  arrange(NUSP)
#rmarkdown::paged_table(data)
knitr::kable(data, booktabs = TRUE, longtable = TRUE)
``` 

# Resumo das avaliações

```{r echo = FALSE, warning = FALSE, message = FALSE}
data %>% 
  select(-Part) %>% 
  pivot_longer(-NUSP, names_to = "key", values_to = "value") %>% 
  filter(value != 0) %>% 
  group_by(key) %>% 
  ggplot(aes(x = key, y = value)) +
  geom_boxplot() +
  xlab("Avaliação") +
  ylab("Nota")
``` 
