---
title: "Testes de Hipótese"
author: "Rafael B. Stern"
highlight: true
date: ""
type: book
weight: 70
bibliography: refs.bib
---

É comum que queiramos saber o quanto uma amostra corrobora uma hipótese científica. Neste caso, podemos aplicar um teste de hipótese, isto é, um procedimento que decidirá se a hipótese é ou não rejeitada diante da amostra obtida. A hipótese que está sendo testado é comumente chamada de **hipótese nula**, $H_0$.

Por exemplo, considere que $X_1, \ldots, X_n$ indicam a procedência em processos independentes e que $X_i \sim \text{Bernoulli}(\theta)$. Uma possível hipótese é a de que a taxa populacional de procedência é 50\%, isto é $H_0: \theta = 0.5$.

# Tipos de erro

Existem $4$ possíveis resultados que podem decorrer de um teste de hipótese. Note que o teste de hipótese pode rejeitar ou não rejeitar a hipótese nula e, também, esta hipótese pode ser verdadeira ou falsa. Assim, existem $4$ combinações de resultados possíveis:

- (Acerto) A hipótese nula é verdadeira e não é rejeitada.
- (Acerto) A hipótese nula é falsa e é rejeitada.
- (Erro tipo I) A hipótese nula é verdadeira e é rejeitada.
- (Erro tipo II) A hipótese nula é falsa e não é rejeitada.

```{r echo = FALSE, message = FALSE, warning = FALSE, results='asis'}
#erros = data.frame(V1 = c("Rejeita H", "Não rejeita H"),
#                   V2 = c("Erro tipo I", "Acerto"),
#                   V3 = c("Acerto", "Erro tipo II"))
#colnames(erros) = c("", "H é verdadeira", "H é falsa")
#DT::datatable(erros, rownames = FALSE, options = list(pageLength = 5))
```

Note que existe um balanço entre  os erros tipo I e II. Por exemplo, se quiséssemos  que a probabilidade de cometer um erro tipo I fosse 0, então poderíamos nunca rejeitar H. Contudo, neste caso, a probabilidade de cometerum erro tipo II seria 1. Analogamente, se sempre rejeitarmos H, então as probabilidades de erro tipo I e II serão, respectivamente, 1 e 0. Na prática, rejeitamos $H_0$ quando  os dados oferecem evidência contrária a este hipótese. Assim, buscamos que as probabilidades de cometer um erro tipo I ou um erro tipo II sejam baixas.

Uma outra observação importante é que, em geral, não sabemos se cometemos um erro em um teste de hipótese. Para saber se $H_0$ é verdadeiro ou não, seria necessária observar a população.
Como usualmente só somos capazes de observar a amostra, não somos capazes de determinar se $H_0$ é verdadeiro ou não. Assim, não sabemos se o resultado do teste de hipótese foi um acerto ou um erro.

Apesar da limitação acima, podemos controlar  as probabilidades de erro tipo I e II de um teste. Isto é, podemos desenvolver testes que, antes de observar o banco de dados, tenham uma baixa probabilidade de cometer um erro. 

Convecionou-se que a hipótese nula deve ser escolhida de tal forma que  o erro tipo I seja mais grave que o erro tipo II. Por exemplo, pode ser mais grave concluir que um rio não está poluído quando ele está poluído do que concluir que ele está poluído quando de fato não está. Assim, neste caso, tomaríamos a hipótese nula como aquela de que o rio está poluído, pois assim o erro tipo I seria o de rejeitar que o rio está poluído quando ele de fato está. Similarmente, a hipótese científica tomada como hipótese nula geralmente é o *status quo*.

Como o erro tipo I é o mais grave, construímos testes de hipótese que diretamente controlam a probabilidade de erro tipo I. Formalmente, determinaremos testes de hipótese tais que o erro tipo I seja menor que um valor pré-determinado, $\alpha$. É comum que $\alpha$ seja chamado de 
**nível de significância** do teste.

## Exemplo: Amostra Bernoulli

Considere que $X_1, \ldots, X_n$ indicam a procedência em processos independentes e que $X_i \sim \text{Bernoulli}(\theta)$. Uma possível hipótese é a de que a taxa populacional de procedência é 50\%, isto é $H_0: \theta = 0.5$. Para controlar o erro tipo I em $\alpha$, rejeitamos $H_0$ se

$$|\bar{X}-0.5| > \frac{0.5 \cdot qnorm(1-0.5\alpha)}{\sqrt{n}}.$$
**Observação**: Verifique $H_0$ é rejeitado quando o intervalo de confiança 95\% para $\theta$ não contém o valor $0.5$.

## Exemplo: Amostra Normal

Considere que $X_1, \ldots, X_n$ indicam o valor da causa em processos independentes e que $X_i \sim \text{N}(\mu,\sigma^2)$. Rejeitamos $H_0: \mu = \mu_0$ se

$$|\bar{X}-\mu_0| > \frac{S \cdot qnorm(1-0.5\alpha)}{\sqrt{n}}.$$
**Observação**: Verifique $H_0$ é rejeitado quando o intervalo de confiança 95\% para $\mu$ não contém o valor $\mu_0$.

# P-valor

Na amostra estudada no exemplo anterior, 
verificamos que se fixássemos $\alpha = 0.05$,
então o teste rejeitaria a hipótese nula.
Por outro lado, se fixássemos $\alpha = 0.01$,
o teste não rejeitaria a hipótese nula.
Isto ocorre pois quanto menor o valor de $\alpha$,
mais o teste fica conservador em rejeitar $H_0$.
Decorre deste comportamento que,
enquanto que para valores "grandes" de $\alpha$, 
o teste rejeitará $H_0$, 
para valores "pequenos" de $\alpha$
o teste não rejeitará $H_0$.

Um valor de interesse é o menor $\alpha$
tal que o teste rejeita $H_0$ para a amostra observada.
Este $\alpha^*$ é comumente chamado de **p-valor**.
Este valor pode ser muito útil
para compartilhar resultados.
Note que, para a amostra observada,
se um pesquisador fixar um $\alpha > \alpha^*$,
então ele rejeitará $H_0$. Por outro lado,
se ele fixar $\alpha < \alpha^*$, 
então não rejeitará $H_0$. Assim,
somente comparando o p-valor com o $\alpha$ fixado,
é possível saber o resultado do teste.
Portanto, mesmo pesquisadores fixando
níveis de significância diferentes podem
saber o resultado do teste de hipótese apenas
observando o p-valor.

# Referências 
